name: Python Tests

on:
  pull_request:
    branches: ["master", "develop"]

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install black isort flake8
      - run: black --check src
      - run: isort --check-only src
      - run: flake8 src

  migrations:
    name: Check Missing Migrations
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -e .[test] # assumes extras_require for test deps
      - run: python develop/manage.py makemigrations --check --dry-run

  test:
    name: Django ${{ matrix.django-version }} on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: [lint, migrations]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        django-version: ["3.1", "3.2", "4.2", "5.0"]
        exclude:
          - python-version: "3.10"
            django-version: "5.0" # Django 5.0 requires Python >=3.11
          - python-version: "3.11"
            django-version: "3.1" # Django 3.1 does not support Python 3.11+
          - python-version: "3.12"
            django-version: "3.1" # Django 3.1 does not support Python 3.12+
          - python-version: "3.13"
            django-version: "3.1" # Django 3.1 does not support Python 3.13
          - python-version: "3.12"
            django-version: "3.2" # Django 3.2 does not support Python 3.12+
          - python-version: "3.13"
            django-version: "3.2" # Django 3.2 does not support Python 3.13
          - python-version: "3.13"
            django-version: "4.2" # Django 4.2 does not support Python 3.13
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[test]"
          python -m pip install "Django==${{ matrix.django-version }}"

      - name: Test with Pytest
        run: |
          python -m pytest src/siteconfigs
        env:
          DJANGO_DEBUG: 1
